[book]
authors = ["fastEater"]
language = "en"
src = "src"
title = "USD8 Docs"

[output.html]
mathjax-support = true
default-theme = "Navy"
additional-js = ["analytics.js"]

[build]
build-dir = "./docs"